### ISSUE TITLE
Run containerised / docker-compose support?

### ISSUE THREAD

**Issue by sammcj** [painebenjamin/app.enfugue.ai#47]
Just wondering if there’s any plans to have this bundled up into a container image and perhaps docker-compose?

This would make it really easy for people to both try it out but also run it on their home servers etc…

**Comment by painebenjamin** [comment]
Hello, thank you for the suggestion!

You have impeccable timing; I just got the container registry up and running yesterday, and the docker version just passed all my automated tests.

I'm going to do a little more testing before I make an announcement post and do a full tag of `0.2.1`, but it's available now if you'd like to try it. These are the in-progress instructions:

# Running Containerized

Since this requires a GPU for effective operation, your host machine must have a GPU and be able to host GPU-accelerated Docker containers. At the current moment, this is only available using the [Nvidia Container Toolkit](https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/latest/index.html), available for Linux machines. You must install this toolkit and then restart your the Docker daemon before you can launch Enfugue with GPU acceleration.

## Pulling the Container

The container is available directly off the Github Container Repository, it can be pulled like this:

```sh
docker pull ghcr.io/painebenjamin/app.enfugue.ai:latest
```

## Testing Capabilities

To check if the container is working and can communicate with your GPU, you can run the `version` command in the container.

```sh
docker run --rm --gpus all --runtime nvidia ghcr.io/painebenjamin/app.enfugue.ai:latest version                         
```

This is the expected result:

```sh
==========
== CUDA ==
==========

CUDA Version 11.7.1

Container image Copyright (c) 2016-2023, NVIDIA CORPORATION & AFFILIATES. All rights reserved.

This container image and its contents are governed by the NVIDIA Deep Learning Container License.
By pulling and using the container, you accept the terms and conditions of this license:
https://developer.nvidia.com/ngc/nvidia-deep-learning-container-license

A copy of this license is made available in this container at /NGC-DL-CONTAINER-LICENSE for your convenience.

Enfugue v.0.2.1
Torch v.1.13.1+cu117

AI/ML Capabilities:
---------------------
Device type: cuda
CUDA: Ready
TensorRT: Ready
DirectML: Unavailable
MPS: Unavailable
```

## Running

The basic run command is:

```sh
docker run --rm --gpus all --runtime nvidia -v ${{ YOUR CACHE DIRECTORY }}:/root/.cache -p 45554:45554 ghcr.io/painebenjamin/app.enfugue.ai:latest run
```

Import arguments are:
1. Passing `--gpus` is essential to tell Docker which GPUs to permit the container to user.
2. Pass `--runtime nvidia` to force Docker to use the Nvidia runtime.
3. Pass `-v` to mount a volume of your choice to `/root/.cache`, which is the parent directory where Enfugue looks for files, downloads checkpoints, etc. The directories can also be changed in the UI as needed to anything else.
4. Pass `-p` to bind the local port `45554` to the container port `45554`. 

You'll then be able to access to UI at https://app.enfugue.ai:45554. See below for information on changing the port.

### Networking and Configuration

Enfugue uses a domain-based approach to allow for SSL encryption, enabling some browser features. For this reason, Enfugue uses the domain `app.enfugue.ai`, which resolves to the loopback address, `127.0.0.1`. If you want to run Enfugue somewhere else than your local machine, you have two options:

1. The easiest way to make things work is to put an entry in your `hosts` file overriding `app.enfugue.ai` to the IP address of the machine running Enfugue. No other configuration is necessary if you do it this way.
2. Configure `Enfugue` to use a different domain (or no domain at all).

See [Configuration for Advanced Users](https://github.com/painebenjamin/app.enfugue.ai/wiki/Configuration-for-Advanced-Users) on how to use configuration files. You will need to ensure any configuration file passed can be read by the Docker container - this guide uses environment variables for ease-of-use.

Use a combination of `SERVER_SECURE`, `SERVER_DOMAIN` and `SERVER_PORT` to control how Enfugue assembles URLs and listens to requests.

- Set `SERVER_DOMAIN` to your desired domain name or IP address.
- Set `SERVER_PORT` to the desired port to listen to, or default to 45554.
- Set `SERVER_SECURE` to 1/True/Yes to use HTTPS, or anything else for HTTP. *The default configuration uses SSL, so this must be explicitly disabled.*
    - If you want to use HTTPS and aren't using `app.enfugue.ai`, you'll need to provide your own certificate with `SERVER_CERT` and key with `SERVER_KEY`. You can also provide your own chain with `SERVER.CHAIN`.

**Comment by sammcj** [comment]
Oh wow, wasn't expecting that so quickly!

I've just done a quick check and the image runs:

```
latest: Pulling from painebenjamin/app.enfugue.ai
....
fedba0b9c0e3: Pull complete
Digest: sha256:596807e766bbc0adc4f3f276901459dece88a3d9088982db33a235d1c8329691
Status: Downloaded newer image for ghcr.io/painebenjamin/app.enfugue.ai:latest
Enfugue v.0.2.1
Torch v.1.13.1+cu117

AI/ML Capabilities:
---------------------
Device type: cuda
CUDA: Ready
TensorRT: Ready
DirectML: Unavailable
MPS: Unavailable
```

I'll do a proper test and let you know how it goes.

Here's a docker-compose for you:

```yaml
  enfugue:
    image: ghcr.io/painebenjamin/app.enfugue.ai:latest
    container_name: enfugue
    restart: unless-stopped
    profiles:
      - enfugue                 # Optional
    shm_size: "2gb"             # Optional (Gives enfugue access to more shared memory)
    security_opt:
      - no-new-privileges:true  # Optional
    runtime: nvidia
    environment:
      - SERVER_DOMAIN=my-cool-server
      - SERVER_PORT=45554
      - SERVER_SECURE=0
      - PUID=1001               # Optional (set to your non-root user)
      - PGID=1001               # Optional (set to your non-root group)
      - UMASK=002               # Optional
      - TZ=${TZ}                # Optional (set to your timezone)
    ports:
      - "45554:45554"
    volumes:
      - /mnt/REPLACEME/enfugue/cache:/root/.cache
      - /etc/localtime:/etc/localtime:ro
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu, compute]
```
